### ISSUE TITLE
Add public water rate feature

### ISSUE THREAD

**Issue by homubee** [homubee/WaterRate#1]
## 작업 설명
> 공용 수도 관련 작업 사항
데이터 모델 클래스, 뷰, 액티비티 모두 개발해야 함

## TODO
- [x] 모델 클래스 작성
- [x] 리사이클러 뷰 어댑터 작성
- [x] 내용 리스트 뷰 작성
- [x] 내용 작성용 입력폼 뷰 작성
- [x] 공용 수도 초기화 관련 액티비티 작성
