### ISSUE TITLE
Add Calculation Algorithm

### ISSUE THREAD

**Issue by homubee** [homubee/WaterRate#11]
## 작업 설명
> 계산 알고리즘 추가
금월지침, 사용량 입력 받아 수도 요금 계산 및 분배

## TODO
- [x] 금월지침/사용량 입력 받는 액티비티/뷰 구성
- [x] 알고리즘 결정 및 구현
- [x] 계산 결과 출력 액티비티/뷰 구성
