### ISSUE TITLE
Improve result page view design

### ISSUE THREAD

**Issue by homubee** [homubee/WaterRate#16]
## 작업 설명
> 계산 결과 페이지 디자인 개선
표 관련 사이즈 변경, 글씨체, 정렬 등 전반적 개선

## TODO
- [x] 제목 변경
- [x] 주요 사항 볼드체 적용
- [x] 숫자 정렬 변경
-  [x] ~~설비 위치 하단으로 이동~~ -> 추후 재조정
- [x] 표, 이미지 크기 비율 조정
