### ISSUE TITLE
Improve system vulnerability

### ISSUE THREAD

**Issue by homubee** [homubee/WaterRate#18]
## 작업 설명
> 중요 취약점 개선 작업
지침 한계(9999)에 대한 적용
name에 대한 중복 방지

## TODO
- [x] 지침 한계 체크 (입력 받을 시)
- [x] 지침 오버플로우 계산 시스템
- [x] name 중복 방지 체크

## 참고사항
지침 오버플로우는 전월지침이 9998인데, 금월지침이 5인 상황, 실제 사용량은 7이므로, 이에 대한 계산 처리 필요함
db 내에 primary key는 _id지만, 실제 사용하는 것은 name이기 때문에 이에 대한 중복 방지 처리가 필요함
