### ISSUE TITLE
Add no-private waterRate type

### ISSUE THREAD

**Issue by homubee** [homubee/WaterRate#20]
## 작업 설명
> 공용 수도만 있고 개인 수도 없는 상가 타입 추가

## TODO
- [x] 신규 타입 입력 받도록 입력폼 수정
- [x] 신규 타입 예외 처리(입력 받은 내용이 없어도 처리 가능하도록)
- [x] 모델 클래스에 신규 타입 정보 추가
- [x] 신규 타입 계산 처리
- [x] 신규 타입 출력 처리(내용이 없으므로 공백으로 보여주도록)

## 참고사항
파일 위치는 별도 폴더를 생성하거나 찾기 쉬운 적당한 폴더에 저장하도록 함
개인 수도 없는 경우는 불필요하게 지침 입력 받을 필요가 없으므로 해당 부분 편의성을 개선하고자 하는 것
(현재는 0을 입력하여 사용자가 임의로 처리하는 방식)
