### ISSUE TITLE
Improve minor details

### ISSUE THREAD

**Issue by homubee** [homubee/WaterRate#22]
## 작업 설명
> 자잘한 세부사항 개선
파일 이름 적절하게 변경, 파일 저장 위치 찾기 쉽도록 변경
짤림, 텍스트 오류 등 기타 뷰 개선

## TODO
- [x] 파일 저장 이름 변경
- [x] 파일 저장 위치 변경
- [x] 뷰 개선 (짤림, 텍스트, etc.)
