### ISSUE TITLE
Improve minor design feature

### ISSUE THREAD

**Issue by homubee** [homubee/WaterRate#24]
## 작업 설명
> 앱 테마, 툴바 텍스트 등 기타 디자인 사항 개선

## TODO
- [x] 앱 테마 결정 및 적용
- [x] 앱 아이콘 설정
- [x] 액션바 텍스트 개선
- [x] 텍스트 사이즈 및 색상 재조정
- [x] 출력 표 사이즈 조절 기능
- [x] 앱 정보, 오픈소스 라이센스 추가
