### ISSUE TITLE
Add private water rate feature

### ISSUE THREAD

**Issue by homubee** [homubee/WaterRate#3]
## 작업 설명
> 개인 수도 관련 작업 사항
데이터 모델 클래스, 뷰, 액티비티 모두 개발해야 함
공용 수도 부분 연동 작업 필요

## TODO
- [x] 공용 수도 데이터 인텐트 전달
- [x] 모델 클래스 작성
- [x] 리사이클러뷰 어댑터 작성
- [x] 내용 확인 뷰 작성
- [x] 내용 작성용 입력폼 다이얼로그 작성
- [x] 공용 수도 데이터 갱신 - 클래스 구조 변경 필요
- [x] 개인 수도 액티비티 작성

## 참고사항
공용 수도 데이터에 개인 수도 목록 리스트가 필요함
