### ISSUE TITLE
Add SQLite DB

### ISSUE THREAD

**Issue by homubee** [homubee/WaterRate#9]
## 작업 설명
> SQLite DB 추가하여 입력 받은 내용 저장, DB에서는 데이터 저장 및 읽기, 초기화 기능 등이 제공되어야 함

## TODO
- [x] 액션바 버튼 추가
- [x] DB 테이블 설계
- [x] DB에 데이터 저장
- [x] DB 초기화 기능
- [x] DB 데이터 확인

## 참고사항
DB 데이터 확인은 CalculateActivity에서 리사이클러뷰 임의로 추가해 보여주는 방식으로 진행
